// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalBusinessSystem.Data;

#nullable disable

namespace UniversalBusinessSystem.Data.Migrations
{
    [DbContext(typeof(UniversalBusinessSystemDbContext))]
    partial class UniversalBusinessSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryPointClass")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1212),
                            Description = "Manage users and roles",
                            EntryPointClass = "UniversalBusinessSystem.Modules.UserManagement.UserManagementModule",
                            IsActive = true,
                            IsRequired = true,
                            Key = "user_management",
                            ModuleType = 1,
                            Name = "User Management",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1239),
                            Description = "Manage products and categories",
                            EntryPointClass = "UniversalBusinessSystem.Modules.Inventory.InventoryModule",
                            IsActive = true,
                            IsRequired = true,
                            Key = "inventory_management",
                            ModuleType = 1,
                            Name = "Inventory Management",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1249),
                            Description = "Manage product variants for clothing",
                            EntryPointClass = "UniversalBusinessSystem.Modules.Variants.VariantsModule",
                            IsActive = true,
                            IsRequired = false,
                            Key = "size_color_variants",
                            ModuleType = 7,
                            Name = "Size/Color Variants",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1257),
                            Description = "Manage product warranties",
                            EntryPointClass = "UniversalBusinessSystem.Modules.Warranty.WarrantyModule",
                            IsActive = true,
                            IsRequired = false,
                            Key = "warranty_management",
                            ModuleType = 7,
                            Name = "Warranty Management",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1264),
                            Description = "Weight-based pricing for groceries",
                            EntryPointClass = "UniversalBusinessSystem.Modules.WeightPricing.WeightPricingModule",
                            IsActive = true,
                            IsRequired = false,
                            Key = "weight_pricing",
                            ModuleType = 7,
                            Name = "Weight-based Pricing",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1270),
                            Description = "Track IMEI numbers for mobile devices",
                            EntryPointClass = "UniversalBusinessSystem.Modules.IMEI.IMEIModule",
                            IsActive = true,
                            IsRequired = false,
                            Key = "imei_tracking",
                            ModuleType = 7,
                            Name = "IMEI Tracking",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AssemblyName = "UniversalBusinessSystem.Modules",
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1276),
                            Description = "Track batch numbers and expiry dates",
                            EntryPointClass = "UniversalBusinessSystem.Modules.BatchExpiry.BatchExpiryModule",
                            IsActive = true,
                            IsRequired = false,
                            Key = "batch_expiry",
                            ModuleType = 7,
                            Name = "Batch & Expiry",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabasePath")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShopTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.HasIndex("ShopTypeId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.OrganizationModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("OrganizationId", "ModuleId")
                        .IsUnique();

                    b.ToTable("OrganizationModules");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("OrganizationId", "UnitId")
                        .IsUnique();

                    b.ToTable("OrganizationUnits");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1348),
                            Description = "View main dashboard",
                            IsActive = true,
                            Key = "dashboard.view",
                            Name = "View Dashboard"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"),
                            Category = 9,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1363),
                            Description = "Access application settings",
                            IsActive = true,
                            Key = "settings.access",
                            Name = "Access Settings"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1376),
                            Description = "View user list",
                            IsActive = true,
                            Key = "users.view",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbc"),
                            Category = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1382),
                            Description = "Create new users",
                            IsActive = true,
                            Key = "users.create",
                            Name = "Create Users"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            Category = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1388),
                            Description = "Edit existing users",
                            IsActive = true,
                            Key = "users.edit",
                            Name = "Edit Users"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbe"),
                            Category = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1394),
                            Description = "Delete users",
                            IsActive = true,
                            Key = "users.delete",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbf"),
                            Category = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1401),
                            Description = "Manage user roles and permissions",
                            IsActive = true,
                            Key = "roles.manage",
                            Name = "Manage Roles"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1406),
                            Description = "View product list",
                            IsActive = true,
                            Key = "products.view",
                            Name = "View Products"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccd"),
                            Category = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1415),
                            Description = "Create new products",
                            IsActive = true,
                            Key = "products.create",
                            Name = "Create Products"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccce"),
                            Category = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1420),
                            Description = "Edit existing products",
                            IsActive = true,
                            Key = "products.edit",
                            Name = "Edit Products"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccf"),
                            Category = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1429),
                            Description = "Delete products",
                            IsActive = true,
                            Key = "products.delete",
                            Name = "Delete Products"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd0"),
                            Category = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1435),
                            Description = "View category list",
                            IsActive = true,
                            Key = "categories.view",
                            Name = "View Categories"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            Category = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1440),
                            Description = "Create new categories",
                            IsActive = true,
                            Key = "categories.create",
                            Name = "Create Categories"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            Category = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1445),
                            Description = "Edit existing categories",
                            IsActive = true,
                            Key = "categories.edit",
                            Name = "Edit Categories"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd3"),
                            Category = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1450),
                            Description = "Delete categories",
                            IsActive = true,
                            Key = "categories.delete",
                            Name = "Delete Categories"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Category = 10,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1454),
                            Description = "View available modules",
                            IsActive = true,
                            Key = "modules.view",
                            Name = "View Modules"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeef"),
                            Category = 10,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1459),
                            Description = "Activate/deactivate modules",
                            IsActive = true,
                            Key = "modules.manage",
                            Name = "Manage Modules"
                        });
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attributes")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackStock")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("OrganizationId", "Barcode")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OrganizationId", "OrderNumber")
                        .IsUnique();

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.ShopType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModules")
                        .HasColumnType("text");

                    b.Property<string>("DefaultUnits")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(591),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\"]",
                            DefaultUnits = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\"]",
                            Description = "General retail store",
                            IsActive = true,
                            Name = "General Store",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(626),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\",\"33333333-3333-3333-3333-333333333333\"]",
                            DefaultUnits = "[\"11111111-1111-1111-1111-111111111111\"]",
                            Description = "Fashion and clothing store",
                            IsActive = true,
                            Name = "Clothing/Boutique",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(634),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\",\"44444444-4444-4444-4444-444444444444\"]",
                            DefaultUnits = "[\"11111111-1111-1111-1111-111111111111\"]",
                            Description = "Electronics and appliances",
                            IsActive = true,
                            Name = "Electronics",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(641),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\",\"55555555-5555-5555-5555-555555555555\"]",
                            DefaultUnits = "[\"22222222-2222-2222-2222-222222222222\",\"33333333-3333-3333-3333-333333333333\"]",
                            Description = "Grocery and food items",
                            IsActive = true,
                            Name = "Grocery",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(647),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\",\"66666666-6666-6666-6666-666666666666\"]",
                            DefaultUnits = "[\"11111111-1111-1111-1111-111111111111\"]",
                            Description = "Mobile phones and accessories",
                            IsActive = true,
                            Name = "Mobile Shop",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(653),
                            DefaultModules = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\",\"77777777-7777-7777-7777-777777777777\"]",
                            DefaultUnits = "[\"11111111-1111-1111-1111-111111111111\",\"22222222-2222-2222-2222-222222222222\"]",
                            Description = "Pharmacy and medical supplies",
                            IsActive = true,
                            Name = "Pharmacy",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdjustedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedBy");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseConversionFactor")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BaseUnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseConversionFactor = 1m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1049),
                            IsActive = true,
                            Name = "Piece",
                            SortOrder = 1,
                            Symbol = "pcs",
                            UnitType = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseConversionFactor = 1m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1080),
                            IsActive = true,
                            Name = "Kilogram",
                            SortOrder = 2,
                            Symbol = "kg",
                            UnitType = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseConversionFactor = 1m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1089),
                            IsActive = true,
                            Name = "Liter",
                            SortOrder = 3,
                            Symbol = "L",
                            UnitType = 4
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BaseConversionFactor = 1m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1095),
                            IsActive = true,
                            Name = "Meter",
                            SortOrder = 4,
                            Symbol = "m",
                            UnitType = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BaseConversionFactor = 0.001m,
                            BaseUnitId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1102),
                            IsActive = true,
                            Name = "Gram",
                            SortOrder = 5,
                            Symbol = "g",
                            UnitType = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BaseConversionFactor = 0.001m,
                            BaseUnitId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1112),
                            IsActive = true,
                            Name = "Milliliter",
                            SortOrder = 6,
                            Symbol = "mL",
                            UnitType = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BaseConversionFactor = 1m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1120),
                            IsActive = true,
                            Name = "Box",
                            SortOrder = 7,
                            Symbol = "box",
                            UnitType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BaseConversionFactor = 12m,
                            CreatedAt = new DateTime(2025, 12, 5, 10, 13, 22, 408, DateTimeKind.Utc).AddTicks(1129),
                            IsActive = true,
                            Name = "Dozen",
                            SortOrder = 8,
                            Symbol = "doz",
                            UnitType = 1
                        });
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationExpires")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Category", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("Categories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Organization", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.ShopType", null)
                        .WithMany("Organizations")
                        .HasForeignKey("ShopTypeId");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.OrganizationModule", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Module", "Module")
                        .WithMany("OrganizationModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("ActiveModules")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("Units")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Unit", "Unit")
                        .WithMany("OrganizationUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Product", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("Products")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Role", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.StockAdjustment", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("AdjustedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Supplier", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("Suppliers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Unit", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.User", b =>
                {
                    b.HasOne("UniversalBusinessSystem.Core.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversalBusinessSystem.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Module", b =>
                {
                    b.Navigation("OrganizationModules");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Organization", b =>
                {
                    b.Navigation("ActiveModules");

                    b.Navigation("Categories");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("StockAdjustments");

                    b.Navigation("Suppliers");

                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.ShopType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("UniversalBusinessSystem.Core.Entities.Unit", b =>
                {
                    b.Navigation("OrganizationUnits");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
